### ISSUE TITLE
I get a NullPointerException with saml authorization

### ISSUE THREAD

**Issue by garpinc** [pac4j/spring-security-pac4j-demo#12]
SPRING SECURITY PAC4J DEMO 11:59:19.242 [qtp1727026317-17] WARN  o.o.x.i.BasicSignatureSigningParametersResolver - Validation failure: Unable to resolve signing credential
[WARNING] /callback
org.pac4j.saml.exceptions.SAMLException: java.lang.NullPointerException
        at org.pac4j.saml.crypto.DefaultSignatureSigningParametersProvider.build(DefaultSignatureSigningParametersProvider.java:81)
        at org.pac4j.saml.sso.impl.SAML2WebSSOMessageSender.sendMessage(SAML2WebSSOMessageSender.java:92)
        at org.pac4j.saml.sso.impl.SAML2WebSSOMessageSender.sendMessage(SAML2WebSSOMessageSender.java:46)
        at org.pac4j.saml.sso.impl.SAML2WebSSOProfileHandler.send(SAML2WebSSOProfileHandler.java:50)
        at org.pac4j.saml.sso.impl.SAML2WebSSOProfileHandler.send(SAML2WebSSOProfileHandler.java:34)
        at org.pac4j.saml.client.SAML2Client.retrieveRedirectAction(SAML2Client.java:231)
        at org.pac4j.core.client.IndirectClient.getCredentials(IndirectClient.java:181)
        at org.pac4j.springframework.security.web.ClientAuthenticationFilter.attemptAuthentication(ClientAuthenticat
ionFilter.java:88)
        at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:217)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
        at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:120)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
        at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(
WebAsyncManagerIntegrationFilter.java:53)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
        at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersist
enceFilter.java:91)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
        at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:213)
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:176)
        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1667)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1113)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1047)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:109)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
        at org.eclipse.jetty.server.Server.handle(Server.java:517)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:302)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:238)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
        at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:57)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213
)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
        at org.pac4j.saml.crypto.DefaultSignatureSigningParametersProvider.build(DefaultSignatureSigningParametersProvider.java:70)
        ... 44 more

**Comment by leleuj** [comment]
I haven't been to figure out what's the problem currently. I just switched from TestShib (which was not working) to Okta. The same configuration works in the https://github.com/pac4j/j2e-pac4j-demo.

Any help will be appreciated.

**Comment by garpinc** [comment]
Hmm.. so I spent all night debugging.. The problem seems to be on this line:
        outboundContext.getSecurityParametersContext()
                .setSignatureSigningParameters(this.signatureSigningParametersProvider.build(spDescriptor));

In org.pac4j.saml.sso.impl.SAML2WebSSOMessageSender

In send message first is called:
        final SPSSODescriptor spDescriptor = context.getSPSSODescriptor();
        final IDPSSODescriptor idpssoDescriptor = context.getIDPSSODescriptor();

Now the idpssoDescriptor has signingMethods assigned in the extensions.. The spDescriptor doesn't. Since I don't know much about the details in saml I'm not sure if that's right or not.. What I do know is that causes params to be null in:
org.pac4j.saml.crypto.DefaultSignatureSigningParametersProvider.build(SSODescriptor) on line 63

the null is returned in org.opensaml.xmlsec.impl.BasicSignatureSigningParametersResolver.resolveSingle(CriteriaSet) after validate fails.

Unfortunately I don't know what's supposed to happen which is why I'm not much help but hopefully this debug info might help.. You can join me on skype as well to work it out. I sent u a skype request I think

**Comment by leleuj** [comment]
"spent all night debugging"? Don't you have your own SAML provider configured?

I've done some debugging and the problem seems fairly complicated. With the old TestShib provider, things worked in pac4j even if the provider configuration returns an error.

I need to do more testing on this.

**Comment by garpinc** [comment]
No I don't yet.. The customer just sent me an idp.xml file which appears to have an EntityDescriptor with an IDPSSODescriptor within it.. It doesn't even have on with a SPSSODescriptor. They also sent me some test assertion and some certificate..

My problem is unless I can understand what I need to put in pac4j and see it working then I don't know what to do with this stuff the client gave me.

**Comment by garpinc** [comment]
Actually I'm thinking maybe my intuition is right.. Are you sure pac4j uses the SPSSODescriptor in that file.. If it doesn't and it creates it's own then it needs the same extensions that are in that previous shib file. While debugging it clearly didn't have those extensions in the service provider and the new okta file doesn't even have a service provider descriptor. Hence perhaps that's what changed.. Let me know your thoughts.. :
-        <Extensions>
-            <mdalg:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha512" />
-            <mdalg:DigestMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#sha384" />
-            <mdalg:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256" />
-            <mdalg:DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1" />
-            <mdalg:SigningMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha512" />
-            <mdalg:SigningMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha384" />
-            <mdalg:SigningMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256" />
-            <mdalg:SigningMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1" />
-        </Extensions>

**Comment by leleuj** [comment]
Indeed, the descriptor just have the IdP information for Okta, but I don't think it's the problem. Because I have re-enabled TestShib and it works for J2E and not for Spring Security (and the TestShib metadata have IdP and SP descriptors), so I think the problem comes from this change: https://github.com/pac4j/pac4j/commit/d7c69a120e7912431e4caf8394c476214a95cd64#diff-f22e401d683fa6acc10aeb09837291eb

Stay tuned, I'm checking that...

**Comment by leleuj** [comment]
I found out the problem. Here is the fix: https://github.com/pac4j/pac4j/commit/0f3fc69e648c9f3adaf5835415dd7e285cfea1d6

It works now for TestShib and Okta!
