### ISSUE TITLE
Error for /callback java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by lionelg3** [pac4j/spring-security-pac4j-demo#15]
When the callback happen in the "Protected url by Google OpenID Connect" exemple. I have the following error : 
`java.lang.NoSuchMethodError: org.pac4j.core.profile.ProfileHelper.buildUserProfileByClassCompleteName(Ljava/lang/String;)Lorg/pac4j/core/profile/CommonProfile;
	at org.pac4j.oidc.profile.creator.OidcProfileCreator.create(OidcProfileCreator.java:118)
	at org.pac4j.oidc.profile.creator.OidcProfileCreator.create(OidcProfileCreator.java:45)
	at org.pac4j.core.client.IndirectClientV2.retrieveUserProfile(IndirectClientV2.java:69)
	at org.pac4j.core.client.BaseClient.getUserProfile(BaseClient.java:60)
	at org.pac4j.core.engine.DefaultCallbackLogic.perform(DefaultCallbackLogic.java:76)
	at org.pac4j.springframework.security.web.CallbackFilter.doFilter(CallbackFilter.java:46)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:66)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:106)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)`

In my own test app using Pac4J 1.9.2 and spring-security-pac4j 2.0.0 connecting MitreID I have exacly the same issue. 
**Look like a dependency error :(**

**Comment by leleuj** [comment]
See: http://www.pac4j.org/docs/backward-compatibility.html

It will be "fixed" by the 2.0.1 release. For now, you can explicitly pull the `pac4j-core` version 1.9.2 dependency.

**Comment by lionelg3** [comment]
Ok, great thank you for your help !

**Comment by leleuj** [comment]
I just released the version 2.0.1. It should be available in the Maven central repository in a few hours.

**Comment by lionelg3** [comment]
Work fine with version spring-security-pac4j version 2.0.1, thank you.
